# Generated by Django 4.2.11 on 2026-05-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Billing'), ('TRAVEL', 'Travel Data')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('raw_payload', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingests', to='companies.company')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
