# Generated by Django 4.2.11 on 2026-05-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=255)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct'), ('SCOPE_2', 'Scope 2 - Indirect (Energy)'), ('SCOPE_3', 'Scope 3 - Indirect (Other)')], max_length=20)),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('calculated_co2e', models.DecimalField(decimal_places=4, help_text='CO2e in kilograms', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUSPICIOUS', 'Flagged for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('anomaly_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='companies.company')),
                ('raw_data_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='uploads.rawdataingest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
